### ISSUE TITLE
Modificar Validación CUI 

### ISSUE THREAD

**Issue by PabloMuralles** [PabloMuralles/cdag#3]
Si uno valida el CUI y el campo esta vacío solo muestra el error del sql -->  **SOLUCIONADO**

**Comment by PabloMuralles** [comment]
Además la validación no acepta letras se debe de modificar esto debido a que algunos pasaportes poseen letras. --> SOLUCIONADO
![WhatsApp Image 2022-11-18 at 11 58 20](https://user-images.githubusercontent.com/46784304/202771787-542689fc-4b31-473c-be81-c187f4529a3f.jpg)

**Comment by PabloMuralles** [comment]
También al únicamente ingresar un numero trae a un participantes por lo la forma en hacer el query para encontrar la participante estén malas. --> SOLUCIONADO
![WhatsApp Image 2022-11-18 at 11 54 50](https://user-images.githubusercontent.com/46784304/202772495-977c9ca5-8d13-4e52-9045-161233ee1e78.jpg)
![WhatsApp Image 2022-11-18 at 11 55 00](https://user-images.githubusercontent.com/46784304/202772498-809ac427-5823-42ea-a258-e50990b5e73e.jpg)
![WhatsApp Image 2022-11-18 at 11 55 19](https://user-images.githubusercontent.com/46784304/202772501-b3a1ee1e-1116-443d-b726-e0cf7a12f7ca.jpg)

**Comment by Deal-RP** [comment]
> 

Terminado
